name: Infrastructure Pipeline

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - develop
          - sit
          - stg
          - prod

jobs:
  vpc:
    name: Deploy VPC
    uses: ./.github/workflows/create_vpc.yml
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit

  parallel-resources:
    needs: vpc
    name: Deploy Parallel Resources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource-config:
          - name: efs
            path: create_efs.yml
          - name: ecs-cluster
            path: create_ecs-cluster.yml
          - name: rds
            path: create_rds.yml
    steps:
      - name: Deploy ${{ matrix.resource-config.name }}
      uses: ./.github/workflows/${{ matrix.resource-config.path }}
      with:
          target-env: ${{ inputs.target-env }}
    secrets: inherit
