name: Infrastructure Pipeline

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - develop
          - sit
          - stg
          - prod
      vpc-cidr:
        description: 'CIDR block for the VPC'
        required: true
        default: '10.0.0.0/16'
      public-subnet-cidr:
        description: 'CIDR block for the public subnet'
        required: true
        default: '["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]'
      private-subnet-cidr:
        description: 'CIDR block for the private subnet'
        required: true
        default: '["10.0.10.0/24", "10.0.11.0/24", "10.0.12.0/24"]'
      rds:
        default: false
        type: boolean
      efs:
        default: false
        type: boolean
      ecs-cluster:
        default: false
        type: boolean

jobs:
  vpc:
    name: Deploy VPC
    uses: ./.github/workflows/create_vpc.yml
    with:
      target-env: ${{ inputs.target-env }}
      vpc-cidr: ${{ inputs.vpc-cidr }}
      public-subnet-cidr: ${{ inputs.public-subnet-cidr }}
      private-subnet-cidr: ${{ inputs.private-subnet-cidr }}
    secrets: inherit

  ecs-cluster:
    name: Deploy ECS Cluster
    needs: vpc
    uses: ./.github/workflows/create_ecs_cluster.yml
    if: ${{ inputs.ecs-cluster }} == true
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit
  
  efs:
    name: Deploy EFS
    needs: vpc
    uses: ./.github/workflows/create_efs.yml
    if: ${{ inputs.efs }} == true
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit

  rds:
    name: Deploy RDS
    needs: vpc
    uses: ./.github/workflows/create_rds.yml
    if: ${{ inputs.ecs-cluster }} == true
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit